# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170420_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='setor',
            name='recebe_chamados',
            field=models.BooleanField(default=False),
        ),
    ]
