language: python

python:
  - "3.5"

before_install:
  - export DJANGO_SETTINGS_MODULE=config.settings.travis

# comando para instalar dependencias
install: 
  - pip install -r requirements.txt
  - pip install codecov
  - wget https://github.com/CMCuritiba/django-cmcldapauth/blob/master/dist/django-cmcldapauth-0.1.tar.gz
  - pip install django-cmcldapauth-0.1.tar.gz

before_script:
  - npm install -g bower
  - npm install -g grunt-cli
  - bower install
  - psql -c 'create database chamados;' -U postgres
  - python manage.py makemigrations --settings=config.settings.travis
  - python manage.py migrate --settings=config.settings.travis
  - python manage.py bower_install
  - python manage.py collectstatic --noinput

# comando para rodas os testes
script: 
  - coverage run manage.py test

after_success:
  codecov