language: python

python:
  - "3.5"

# comando para instalar dependencias
install: 
  - pip install -r requirements.txt
  - pip install codecov

# comando para rodas os testes
script: 
  python manage.py makemigrations
  python manage.py migrate
  coverage run manage.py test --settings=config.settings.travis

after_success:
  codecov