language: python

python:
  - "3.5"

before_install:
  - export DJANGO_SETTINGS_MODULE=config.settings.travis

# comando para instalar dependencias
install: 
  - pip install -r requirements.txt
  - pip install codecov
  - pip install https://github.com/CMCuritiba/django-cmcldapauth/blob/master/dist/django-cmcldapauth-0.1.tar.gz?raw=true

before_script:
  - npm install -g bower
  - npm install -g grunt-cli
  - bower install
  - psql -c 'create database chamados;' -U postgres
  - python manage.py makemigrations autentica core --settings=config.settings.travis
  - python manage.py migrate --settings=config.settings.travis
  - python manage.py bower_install
  - python manage.py collectstatic --noinput
  - psql -c 'CREATE TABLE v_setor (
                set_id serial primary key,
                set_nome character varying(500) not null,
                set_sigla character varying(100) not null,
                set_id_superior integer,
                set_ativo boolean not null, 
                set_tipo character varying(1)
            );' -U postgres

# comando para rodas os testes
script: 
  - coverage run manage.py test

after_success:
  codecov