# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autentica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chefia',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
