# -*- coding: utf-8 -*-
"""
Script que executa carga inicial no BD de chamados
Não execute este script sem ter absoluta certeza do que estiver fazendo
"""

import sys
from django.core.management.base import BaseCommand
from chamadoscmc.core.tests.factories import SetorChamadoFactory, GrupoServicoFactory, ServicoFactory

class Command(BaseCommand):
	help = "Carga inicial no BD de Chamados"

	def add_arguments(self, parser):
		parser.add_argument('--palavra_magica')

	def popula_setor_chamado(self):
		self.stdout.write('...populando SetorChamado')
		SetorChamadoFactory.create(id=1, setor_id=172, recebe_chamados=True, localizacao=False)
		SetorChamadoFactory.create(id=2, setor_id=171, recebe_chamados=False, localizacao=False)
		SetorChamadoFactory.create(id=3, setor_id=36, recebe_chamados=True, localizacao=True)
		SetorChamadoFactory.create(id=4, setor_id=38, recebe_chamados=True, localizacao=False)

	def popula_grupo_servico(self):
		self.stdout.write('...populando GrupoServico')		
		# Suporte
		GrupoServicoFactory.create(id=1, descricao='Impressora', patrimonio_obrigatorio=False, setor_id=1)
		GrupoServicoFactory.create(id=58, descricao='Estação de Trabalho', patrimonio_obrigatorio=False, setor_id=1)
		GrupoServicoFactory.create(id=59, descricao='Rede', patrimonio_obrigatorio=False, setor_id=1)
		GrupoServicoFactory.create(id=60, descricao='Wi-Fi', patrimonio_obrigatorio=False, setor_id=1)
		GrupoServicoFactory.create(id=61, descricao='Libreoffice', patrimonio_obrigatorio=False, setor_id=1)
		GrupoServicoFactory.create(id=62, descricao='Sistemas', patrimonio_obrigatorio=False, setor_id=1)
		GrupoServicoFactory.create(id=63, descricao='Elotech: Apice/AISE', patrimonio_obrigatorio=False, setor_id=1)
		GrupoServicoFactory.create(id=64, descricao='RH Online / Ponto Biométrico', patrimonio_obrigatorio=False, setor_id=1)
		GrupoServicoFactory.create(id=65, descricao='Windows virtual', patrimonio_obrigatorio=False, setor_id=1)
		GrupoServicoFactory.create(id=66, descricao='Infraestrutura', patrimonio_obrigatorio=False, setor_id=1)
		GrupoServicoFactory.create(id=67, descricao='Outros', patrimonio_obrigatorio=False, setor_id=1)

		# Patrimônio
		GrupoServicoFactory.create(id=16, descricao='Mesa', patrimonio_obrigatorio=True, setor_id=3)
		GrupoServicoFactory.create(id=17, descricao='Conexão de mesa', patrimonio_obrigatorio=True, setor_id=3)
		GrupoServicoFactory.create(id=18, descricao='Cadeira', patrimonio_obrigatorio=True, setor_id=3)
		GrupoServicoFactory.create(id=19, descricao='Cadeira fixa', patrimonio_obrigatorio=True, setor_id=3)
		GrupoServicoFactory.create(id=20, descricao='Persiana', patrimonio_obrigatorio=True, setor_id=3)
		GrupoServicoFactory.create(id=22, descricao='Balcão', patrimonio_obrigatorio=True, setor_id=3)
		GrupoServicoFactory.create(id=23, descricao='Gaveteiro', patrimonio_obrigatorio=True, setor_id=3)
		GrupoServicoFactory.create(id=24, descricao='Forno Microondas', patrimonio_obrigatorio=True, setor_id=3)
		GrupoServicoFactory.create(id=25, descricao='Monitor', patrimonio_obrigatorio=True, setor_id=3)
		GrupoServicoFactory.create(id=26, descricao='Gabinete', patrimonio_obrigatorio=True, setor_id=3)
		GrupoServicoFactory.create(id=27, descricao='Impressora', patrimonio_obrigatorio=True, setor_id=3)
		GrupoServicoFactory.create(id=28, descricao='Poltrona', patrimonio_obrigatorio=True, setor_id=3)
		GrupoServicoFactory.create(id=29, descricao='Ventilador', patrimonio_obrigatorio=True, setor_id=3)
		GrupoServicoFactory.create(id=30, descricao='Circulador de ar', patrimonio_obrigatorio=True, setor_id=3)
		GrupoServicoFactory.create(id=31, descricao='Fragmentadora', patrimonio_obrigatorio=True, setor_id=3)
		GrupoServicoFactory.create(id=32, descricao='Longarina', patrimonio_obrigatorio=True, setor_id=3)
		GrupoServicoFactory.create(id=33, descricao='Frigobar', patrimonio_obrigatorio=True, setor_id=3)
		GrupoServicoFactory.create(id=34, descricao='Fogão', patrimonio_obrigatorio=True, setor_id=3)
		GrupoServicoFactory.create(id=35, descricao='Geladeira', patrimonio_obrigatorio=True, setor_id=3)
		GrupoServicoFactory.create(id=36, descricao='Ar condicionado', patrimonio_obrigatorio=True, setor_id=3)
		GrupoServicoFactory.create(id=37, descricao='Condensadora de ar condicionado', patrimonio_obrigatorio=True, setor_id=3)
		GrupoServicoFactory.create(id=38, descricao='Extintor', patrimonio_obrigatorio=True, setor_id=3)
		GrupoServicoFactory.create(id=39, descricao='Desumidificador de papel', patrimonio_obrigatorio=True, setor_id=3)
		GrupoServicoFactory.create(id=40, descricao='Bebedouro', patrimonio_obrigatorio=True, setor_id=3)
		GrupoServicoFactory.create(id=41, descricao='Apoio de pé', patrimonio_obrigatorio=True, setor_id=3)
		GrupoServicoFactory.create(id=42, descricao='Apoio de monitor', patrimonio_obrigatorio=True, setor_id=3)
		GrupoServicoFactory.create(id=43, descricao='Calculadora', patrimonio_obrigatorio=True, setor_id=3)
		GrupoServicoFactory.create(id=44, descricao='Aparelho de fax', patrimonio_obrigatorio=True, setor_id=3)
		GrupoServicoFactory.create(id=45, descricao='Quadro', patrimonio_obrigatorio=True, setor_id=3)
		GrupoServicoFactory.create(id=46, descricao='Switch', patrimonio_obrigatorio=True, setor_id=3)
		GrupoServicoFactory.create(id=47, descricao='Notebook', patrimonio_obrigatorio=True, setor_id=3)
		GrupoServicoFactory.create(id=48, descricao='Câmera fotográfica', patrimonio_obrigatorio=True, setor_id=3)
		GrupoServicoFactory.create(id=49, descricao='Microfone', patrimonio_obrigatorio=True, setor_id=3)
		GrupoServicoFactory.create(id=50, descricao='Liquidificador', patrimonio_obrigatorio=True, setor_id=3)
		GrupoServicoFactory.create(id=51, descricao='Divisória', patrimonio_obrigatorio=True, setor_id=3)
		GrupoServicoFactory.create(id=52, descricao='Gravador', patrimonio_obrigatorio=True, setor_id=3)
		GrupoServicoFactory.create(id=53, descricao='Banqueta', patrimonio_obrigatorio=True, setor_id=3)
		GrupoServicoFactory.create(id=54, descricao='Banco de madeira', patrimonio_obrigatorio=True, setor_id=3)
		GrupoServicoFactory.create(id=55, descricao='Lixeira', patrimonio_obrigatorio=True, setor_id=3)
		GrupoServicoFactory.create(id=56, descricao='Estante', patrimonio_obrigatorio=True, setor_id=3)
		GrupoServicoFactory.create(id=57, descricao='Outros', patrimonio_obrigatorio=True, setor_id=3)
		GrupoServicoFactory.create(id=68, descricao='Armário', patrimonio_obrigatorio=True, setor_id=3)

		# Instalações
		GrupoServicoFactory.create(id=71, descricao="Goteiras", patrimonio_obrigatorio=False, setor_id=4)
		GrupoServicoFactory.create(id=72, descricao="Vazamentos", patrimonio_obrigatorio=False, setor_id=4)
		GrupoServicoFactory.create(id=73, descricao="Banheiros - mau cheiro", patrimonio_obrigatorio=False, setor_id=4)
		GrupoServicoFactory.create(id=74, descricao="Mau cheiro em Geral", patrimonio_obrigatorio=False, setor_id=4)
		GrupoServicoFactory.create(id=75, descricao="Rede de Esgoto - manutenção", patrimonio_obrigatorio=False, setor_id=4)
		GrupoServicoFactory.create(id=76, descricao="Qualidade da água", patrimonio_obrigatorio=False, setor_id=4)
		GrupoServicoFactory.create(id=77, descricao="Grades e Portões com problemas", patrimonio_obrigatorio=False, setor_id=4)
		GrupoServicoFactory.create(id=78, descricao="Vidros", patrimonio_obrigatorio=False, setor_id=4)
		GrupoServicoFactory.create(id=79, descricao="Janelas", patrimonio_obrigatorio=False, setor_id=4)
		GrupoServicoFactory.create(id=80, descricao="Falta de água", patrimonio_obrigatorio=False, setor_id=4)
		GrupoServicoFactory.create(id=81, descricao="Elevadores", patrimonio_obrigatorio=False, setor_id=4)
		GrupoServicoFactory.create(id=84, descricao="CIVIL - Portas, Paredes e Pisos", patrimonio_obrigatorio=False, setor_id=4)
		GrupoServicoFactory.create(id=85, descricao="ELÉTRICA - LÓGICA E TELEFONIA", patrimonio_obrigatorio=False, setor_id=4)


	def popula_servico(self):
		self.stdout.write('...populando Servico')				

		#Suporte
		ServicoFactory.create(id=1, descricao='Troca de tonner', grupo_servico_id=1)
		ServicoFactory.create(id=301, descricao='Não liga', grupo_servico_id=58)
		ServicoFactory.create(id=302, descricao='Usuário não loga', grupo_servico_id=58)
		ServicoFactory.create(id=303, descricao='Reiniciando', grupo_servico_id=58)
		ServicoFactory.create(id=304, descricao='Travando', grupo_servico_id=58)
		ServicoFactory.create(id=305, descricao='Mouse/teclado com defeito', grupo_servico_id=58)
		ServicoFactory.create(id=306, descricao='Monitor não liga', grupo_servico_id=58)
		ServicoFactory.create(id=307, descricao='Monitor desconfigurado', grupo_servico_id=58)
		ServicoFactory.create(id=308, descricao='Não sai áudio', grupo_servico_id=58)
		ServicoFactory.create(id=309, descricao='Criação ou alteração de usuário, senha ou e-mail', grupo_servico_id=59)
		ServicoFactory.create(id=310, descricao='Não acessa ou não aparecem as pastas de rede', grupo_servico_id=59)
		ServicoFactory.create(id=311, descricao='Cota de espaço para pastas de rede', grupo_servico_id=59)
		ServicoFactory.create(id=312, descricao='Cota de espaço para e-mail', grupo_servico_id=59)
		ServicoFactory.create(id=313, descricao='Recuperar backup', grupo_servico_id=59)
		ServicoFactory.create(id=314, descricao='Relatório de navegação na internet', grupo_servico_id=59)
		ServicoFactory.create(id=315, descricao='Não consegue acessar', grupo_servico_id=63)
		ServicoFactory.create(id=316, descricao='Não consegue imprimir', grupo_servico_id=63)
		ServicoFactory.create(id=317, descricao='Nova instalação', grupo_servico_id=63)
		ServicoFactory.create(id=318, descricao='Não imprime', grupo_servico_id=1)
		ServicoFactory.create(id=319, descricao='Impressões manchadas/com falhas', grupo_servico_id=1)
		ServicoFactory.create(id=320, descricao='Cota de impressão', grupo_servico_id=1)
		ServicoFactory.create(id=321, descricao='Relatório de impressões', grupo_servico_id=1)
		ServicoFactory.create(id=323, descricao='Não consegue se conectar', grupo_servico_id=60)
		ServicoFactory.create(id=324, descricao='Não consegue navegar', grupo_servico_id=60)
		ServicoFactory.create(id=325, descricao='Criação de usuário', grupo_servico_id=60)
		ServicoFactory.create(id=327, descricao='Não consegue abrir ou salvar arquivos', grupo_servico_id=61)
		ServicoFactory.create(id=328, descricao='SPL', grupo_servico_id=62)
		ServicoFactory.create(id=329, descricao='SPA', grupo_servico_id=62)
		ServicoFactory.create(id=330, descricao='SAAP', grupo_servico_id=62)
		ServicoFactory.create(id=331, descricao='APL', grupo_servico_id=62)
		ServicoFactory.create(id=332, descricao='Legisladoc', grupo_servico_id=62)
		ServicoFactory.create(id=333, descricao='Não sabe ou não consegue acessar o sistema', grupo_servico_id=64)
		ServicoFactory.create(id=334, descricao='Não abre', grupo_servico_id=65)
		ServicoFactory.create(id=335, descricao='Não acessa pastas de rede', grupo_servico_id=65)
		ServicoFactory.create(id=336, descricao='Não consegue imprimir', grupo_servico_id=65)
		ServicoFactory.create(id=337, descricao='Novo ponto de rede', grupo_servico_id=66)
		ServicoFactory.create(id=338, descricao='Manutenção em ponto de rede', grupo_servico_id=66)
		ServicoFactory.create(id=344, descricao='Travamento', grupo_servico_id=61)

		# Patrimônio
		ServicoFactory.create(id=43, descricao='Troca por defeito', grupo_servico_id=16)		
		ServicoFactory.create(id=45, descricao="Recolhimento para baixa", grupo_servico_id=16)
		ServicoFactory.create(id=44, descricao="Recolhimento por não utilização", grupo_servico_id=16)
		ServicoFactory.create(id=46, descricao="Recolhimento para manutenção", grupo_servico_id=16)
		ServicoFactory.create(id=47, descricao="Solicitação de móvel/equipamento", grupo_servico_id=16)
		ServicoFactory.create(id=48, descricao="Alteração de local ou lotação de móvel/equipamento", grupo_servico_id=16)
		ServicoFactory.create(id=49, descricao="Troca por defeito", grupo_servico_id=17)
		ServicoFactory.create(id=50, descricao="Recolhimento por não utilização", grupo_servico_id=17)
		ServicoFactory.create(id=51, descricao="Recolhimento para baixa", grupo_servico_id=17)
		ServicoFactory.create(id=52, descricao="Recolhimento para manutenção", grupo_servico_id=17)
		ServicoFactory.create(id=53, descricao="Solicitação de móvel/equipamento", grupo_servico_id=17)
		ServicoFactory.create(id=54, descricao="Alteração de local ou lotação de móvel/equipamento", grupo_servico_id=17)
		ServicoFactory.create(id=55, descricao="Troca por defeito", grupo_servico_id=18)
		ServicoFactory.create(id=56, descricao="Recolhimento por não utilização", grupo_servico_id=18)
		ServicoFactory.create(id=57, descricao="Recolhimento para baixa", grupo_servico_id=18)
		ServicoFactory.create(id=58, descricao="Recolhimento para manutenção", grupo_servico_id=18)
		ServicoFactory.create(id=59, descricao="Solicitação de móvel/equipamento", grupo_servico_id=18)
		ServicoFactory.create(id=60, descricao="Alteração de local ou lotação de móvel/equipamento", grupo_servico_id=18)
		ServicoFactory.create(id=61, descricao="Troca por defeito", grupo_servico_id=19)
		ServicoFactory.create(id=62, descricao="Recolhimento por não utilização", grupo_servico_id=19)
		ServicoFactory.create(id=63, descricao="Recolhimento para baixa", grupo_servico_id=19)
		ServicoFactory.create(id=64, descricao="Recolhimento para manutenção", grupo_servico_id=19)
		ServicoFactory.create(id=65, descricao="Solicitação de móvel/equipamento", grupo_servico_id=19)
		ServicoFactory.create(id=66, descricao="Alteração de local ou lotação de móvel/equipamento", grupo_servico_id=19)
		ServicoFactory.create(id=67, descricao="Troca por defeito", grupo_servico_id=20)
		ServicoFactory.create(id=68, descricao="Recolhimento por não utilização", grupo_servico_id=20)
		ServicoFactory.create(id=69, descricao="Recolhimento para baixa", grupo_servico_id=20)
		ServicoFactory.create(id=70, descricao="Recolhimento para manutenção", grupo_servico_id=20)
		ServicoFactory.create(id=71, descricao="Solicitação de móvel/equipamento", grupo_servico_id=20)
		ServicoFactory.create(id=72, descricao="Alteração de local ou lotação de móvel/equipamento", grupo_servico_id=20)
		ServicoFactory.create(id=79, descricao="Troca por defeito", grupo_servico_id=22)
		ServicoFactory.create(id=80, descricao="Recolhimento por não utilização", grupo_servico_id=22)
		ServicoFactory.create(id=81, descricao="Recolhimento para baixa", grupo_servico_id=22)
		ServicoFactory.create(id=82, descricao="Recolhimento para manutenção", grupo_servico_id=22)
		ServicoFactory.create(id=83, descricao="Solicitação de móvel/equipamento", grupo_servico_id=22)
		ServicoFactory.create(id=84, descricao="Alteração de local ou lotação de móvel/equipamento", grupo_servico_id=22)
		ServicoFactory.create(id=85, descricao="Troca por defeito", grupo_servico_id=23)
		ServicoFactory.create(id=86, descricao="Recolhimento por não utilização", grupo_servico_id=23)
		ServicoFactory.create(id=87, descricao="Recolhimento para baixa", grupo_servico_id=23)
		ServicoFactory.create(id=88, descricao="Recolhimento para manutenção", grupo_servico_id=23)
		ServicoFactory.create(id=89, descricao="Solicitação de móvel/equipamento", grupo_servico_id=23)
		ServicoFactory.create(id=90, descricao="Alteração de local ou lotação de móvel/equipamento", grupo_servico_id=23)
		ServicoFactory.create(id=91, descricao="Troca por defeito", grupo_servico_id=24)
		ServicoFactory.create(id=92, descricao="Recolhimento por não utilização", grupo_servico_id=24)
		ServicoFactory.create(id=93, descricao="Recolhimento para baixa", grupo_servico_id=24)
		ServicoFactory.create(id=94, descricao="Recolhimento para manutenção", grupo_servico_id=24)
		ServicoFactory.create(id=95, descricao="Solicitação de móvel/equipamento", grupo_servico_id=24)
		ServicoFactory.create(id=96, descricao="Alteração de local ou lotação de móvel/equipamento", grupo_servico_id=24)
		ServicoFactory.create(id=97, descricao="Troca por defeito", grupo_servico_id=25)
		ServicoFactory.create(id=98, descricao="Recolhimento por não utilização", grupo_servico_id=25)
		ServicoFactory.create(id=99, descricao="Recolhimento para baixa", grupo_servico_id=25)
		ServicoFactory.create(id=100, descricao="Recolhimento para manutenção", grupo_servico_id=25)
		ServicoFactory.create(id=101, descricao="Solicitação de móvel/equipamento", grupo_servico_id=25)
		ServicoFactory.create(id=102, descricao="Alteração de local ou lotação de móvel/equipamento", grupo_servico_id=25)
		ServicoFactory.create(id=103, descricao="Troca por defeito", grupo_servico_id=26)
		ServicoFactory.create(id=104, descricao="Recolhimento por não utilização", grupo_servico_id=26)
		ServicoFactory.create(id=105, descricao="Recolhimento para baixa", grupo_servico_id=26)
		ServicoFactory.create(id=106, descricao="Recolhimento para manutenção", grupo_servico_id=26)
		ServicoFactory.create(id=107, descricao="Solicitação de móvel/equipamento", grupo_servico_id=26)
		ServicoFactory.create(id=108, descricao="Alteração de local ou lotação de móvel/equipamento", grupo_servico_id=26)
		ServicoFactory.create(id=111, descricao="Recolhimento para baixa", grupo_servico_id=27)
		ServicoFactory.create(id=109, descricao="Troca por defeito", grupo_servico_id=27)
		ServicoFactory.create(id=110, descricao="Recolhimento por não utilização", grupo_servico_id=27)
		ServicoFactory.create(id=112, descricao="Recolhimento para manutenção", grupo_servico_id=27)
		ServicoFactory.create(id=113, descricao="Solicitação de móvel/equipamento", grupo_servico_id=27)
		ServicoFactory.create(id=114, descricao="Alteração de local ou lotação de móvel/equipamento", grupo_servico_id=27)
		ServicoFactory.create(id=115, descricao="Troca por defeito", grupo_servico_id=28)
		ServicoFactory.create(id=116, descricao="Recolhimento por não utilização", grupo_servico_id=28)
		ServicoFactory.create(id=117, descricao="Recolhimento para baixa", grupo_servico_id=28)
		ServicoFactory.create(id=118, descricao="Recolhimento para manutenção", grupo_servico_id=28)
		ServicoFactory.create(id=119, descricao="Solicitação de móvel/equipamento", grupo_servico_id=28)
		ServicoFactory.create(id=120, descricao="Alteração de local ou lotação de móvel/equipamento", grupo_servico_id=28)
		ServicoFactory.create(id=121, descricao="Troca por defeito", grupo_servico_id=29)
		ServicoFactory.create(id=122, descricao="Recolhimento por não utilização", grupo_servico_id=29)
		ServicoFactory.create(id=123, descricao="Recolhimento para baixa", grupo_servico_id=29)
		ServicoFactory.create(id=124, descricao="Recolhimento para manutenção", grupo_servico_id=29)
		ServicoFactory.create(id=125, descricao="Solicitação de móvel/equipamento", grupo_servico_id=29)
		ServicoFactory.create(id=126, descricao="Alteração de local ou lotação de móvel/equipamento", grupo_servico_id=29)
		ServicoFactory.create(id=127, descricao="Troca por defeito", grupo_servico_id=30)
		ServicoFactory.create(id=128, descricao="Recolhimento por não utilização", grupo_servico_id=30)
		ServicoFactory.create(id=129, descricao="Recolhimento para baixa", grupo_servico_id=30)
		ServicoFactory.create(id=130, descricao="Recolhimento para manutenção", grupo_servico_id=30)
		ServicoFactory.create(id=131, descricao="Solicitação de móvel/equipamento", grupo_servico_id=30)
		ServicoFactory.create(id=132, descricao="Alteração de local ou lotação de móvel/equipamento", grupo_servico_id=30)
		ServicoFactory.create(id=133, descricao="Troca por defeito", grupo_servico_id=31)
		ServicoFactory.create(id=134, descricao="Recolhimento por não utilização", grupo_servico_id=31)
		ServicoFactory.create(id=135, descricao="Recolhimento para baixa", grupo_servico_id=31)
		ServicoFactory.create(id=136, descricao="Recolhimento para manutenção", grupo_servico_id=31)
		ServicoFactory.create(id=137, descricao="Solicitação de móvel/equipamento", grupo_servico_id=31)
		ServicoFactory.create(id=138, descricao="Alteração de local ou lotação de móvel/equipamento", grupo_servico_id=31)
		ServicoFactory.create(id=173, descricao="Solicitação de móvel/equipamento", grupo_servico_id=31)
		ServicoFactory.create(id=172, descricao="Recolhimento para manutenção", grupo_servico_id=31)
		ServicoFactory.create(id=171, descricao="Recolhimento para baixa", grupo_servico_id=31)
		ServicoFactory.create(id=170, descricao="Recolhimento por não utilização", grupo_servico_id=31)
		ServicoFactory.create(id=169, descricao="Troca por defeito", grupo_servico_id=31)
		ServicoFactory.create(id=144, descricao="Alteração de local ou lotação de móvel/equipamento", grupo_servico_id=32)
		ServicoFactory.create(id=139, descricao="Troca por defeito", grupo_servico_id=32)
		ServicoFactory.create(id=140, descricao="Recolhimento por não utilização", grupo_servico_id=32)
		ServicoFactory.create(id=141, descricao="Recolhimento para baixa", grupo_servico_id=32)
		ServicoFactory.create(id=142, descricao="Recolhimento para manutenção", grupo_servico_id=32)
		ServicoFactory.create(id=143, descricao="Solicitação de móvel/equipamento", grupo_servico_id=32)
		ServicoFactory.create(id=150, descricao="Alteração de local ou lotação de móvel/equipamento", grupo_servico_id=33)
		ServicoFactory.create(id=149, descricao="Solicitação de móvel/equipamento", grupo_servico_id=33)
		ServicoFactory.create(id=148, descricao="Recolhimento para manutenção", grupo_servico_id=33)
		ServicoFactory.create(id=147, descricao="Recolhimento para baixa", grupo_servico_id=33)
		ServicoFactory.create(id=146, descricao="Recolhimento por não utilização", grupo_servico_id=33)
		ServicoFactory.create(id=145, descricao="Troca por defeito", grupo_servico_id=33)
		ServicoFactory.create(id=156, descricao="Alteração de local ou lotação de móvel/equipamento", grupo_servico_id=34)
		ServicoFactory.create(id=151, descricao="Troca por defeito", grupo_servico_id=34)
		ServicoFactory.create(id=152, descricao="Recolhimento por não utilização", grupo_servico_id=34)
		ServicoFactory.create(id=153, descricao="Recolhimento para baixa", grupo_servico_id=34)
		ServicoFactory.create(id=154, descricao="Recolhimento para manutenção", grupo_servico_id=34)
		ServicoFactory.create(id=155, descricao="Solicitação de móvel/equipamento", grupo_servico_id=34)
		ServicoFactory.create(id=162, descricao="Alteração de local ou lotação de móvel/equipamento", grupo_servico_id=35)
		ServicoFactory.create(id=157, descricao="Troca por defeito", grupo_servico_id=35)
		ServicoFactory.create(id=158, descricao="Recolhimento por não utilização", grupo_servico_id=35)
		ServicoFactory.create(id=159, descricao="Recolhimento para baixa", grupo_servico_id=35)
		ServicoFactory.create(id=160, descricao="Recolhimento para manutenção", grupo_servico_id=35)
		ServicoFactory.create(id=161, descricao="Solicitação de móvel/equipamento", grupo_servico_id=35)
		ServicoFactory.create(id=168, descricao="Alteração de local ou lotação de móvel/equipamento", grupo_servico_id=36)
		ServicoFactory.create(id=163, descricao="Troca por defeito", grupo_servico_id=36)
		ServicoFactory.create(id=164, descricao="Recolhimento por não utilização", grupo_servico_id=36)
		ServicoFactory.create(id=165, descricao="Recolhimento para baixa", grupo_servico_id=36)
		ServicoFactory.create(id=166, descricao="Recolhimento para manutenção", grupo_servico_id=36)
		ServicoFactory.create(id=167, descricao="Solicitação de móvel/equipamento", grupo_servico_id=36)
		ServicoFactory.create(id=175, descricao="Troca por defeito", grupo_servico_id=37)
		ServicoFactory.create(id=174, descricao="Alteração de local ou lotação de móvel/equipamento", grupo_servico_id=37)
		ServicoFactory.create(id=176, descricao="Recolhimento por não utilização", grupo_servico_id=37)
		ServicoFactory.create(id=177, descricao="Recolhimento para baixa", grupo_servico_id=37)
		ServicoFactory.create(id=178, descricao="Recolhimento para manutenção", grupo_servico_id=37)
		ServicoFactory.create(id=179, descricao="Solicitação de móvel/equipamento", grupo_servico_id=37)
		ServicoFactory.create(id=180, descricao="Alteração de local ou lotação de móvel/equipamento", grupo_servico_id=37)
		ServicoFactory.create(id=181, descricao="Troca por defeito", grupo_servico_id=38)
		ServicoFactory.create(id=182, descricao="Recolhimento por não utilização", grupo_servico_id=38)
		ServicoFactory.create(id=183, descricao="Recolhimento para baixa", grupo_servico_id=38)
		ServicoFactory.create(id=184, descricao="Recolhimento para manutenção", grupo_servico_id=38)
		ServicoFactory.create(id=185, descricao="Solicitação de móvel/equipamento", grupo_servico_id=38)
		ServicoFactory.create(id=186, descricao="Alteração de local ou lotação de móvel/equipamento", grupo_servico_id=38)
		ServicoFactory.create(id=187, descricao="Troca por defeito", grupo_servico_id=39)
		ServicoFactory.create(id=188, descricao="Recolhimento por não utilização", grupo_servico_id=39)
		ServicoFactory.create(id=189, descricao="Recolhimento para baixa", grupo_servico_id=39)
		ServicoFactory.create(id=190, descricao="Recolhimento para manutenção", grupo_servico_id=39)
		ServicoFactory.create(id=191, descricao="Solicitação de móvel/equipamento", grupo_servico_id=39)
		ServicoFactory.create(id=192, descricao="Alteração de local ou lotação de móvel/equipamento", grupo_servico_id=39)
		ServicoFactory.create(id=193, descricao="Troca por defeito", grupo_servico_id=40)
		ServicoFactory.create(id=194, descricao="Recolhimento por não utilização", grupo_servico_id=40)
		ServicoFactory.create(id=195, descricao="Recolhimento para baixa", grupo_servico_id=40)
		ServicoFactory.create(id=196, descricao="Recolhimento para manutenção", grupo_servico_id=40)
		ServicoFactory.create(id=197, descricao="Solicitação de móvel/equipamento", grupo_servico_id=40)
		ServicoFactory.create(id=198, descricao="Alteração de local ou lotação de móvel/equipamento", grupo_servico_id=40)
		ServicoFactory.create(id=199, descricao="Troca por defeito", grupo_servico_id=41)
		ServicoFactory.create(id=200, descricao="Recolhimento por não utilização", grupo_servico_id=41)
		ServicoFactory.create(id=201, descricao="Recolhimento para baixa", grupo_servico_id=41)
		ServicoFactory.create(id=202, descricao="Recolhimento para manutenção", grupo_servico_id=41)
		ServicoFactory.create(id=203, descricao="Solicitação de móvel/equipamento", grupo_servico_id=41)
		ServicoFactory.create(id=204, descricao="Alteração de local ou lotação de móvel/equipamento", grupo_servico_id=41)
		ServicoFactory.create(id=205, descricao="Troca por defeito", grupo_servico_id=42)
		ServicoFactory.create(id=206, descricao="Recolhimento por não utilização", grupo_servico_id=42)
		ServicoFactory.create(id=207, descricao="Recolhimento para baixa", grupo_servico_id=42)
		ServicoFactory.create(id=208, descricao="Recolhimento para manutenção", grupo_servico_id=42)
		ServicoFactory.create(id=209, descricao="Solicitação de móvel/equipamento", grupo_servico_id=42)
		ServicoFactory.create(id=210, descricao="Alteração de local ou lotação de móvel/equipamento", grupo_servico_id=42)
		ServicoFactory.create(id=211, descricao="Troca por defeito", grupo_servico_id=43)
		ServicoFactory.create(id=212, descricao="Recolhimento por não utilização", grupo_servico_id=43)
		ServicoFactory.create(id=213, descricao="Recolhimento para baixa", grupo_servico_id=43)
		ServicoFactory.create(id=214, descricao="Recolhimento para manutenção", grupo_servico_id=43)
		ServicoFactory.create(id=215, descricao="Solicitação de móvel/equipamento", grupo_servico_id=43)
		ServicoFactory.create(id=216, descricao="Alteração de local ou lotação de móvel/equipamento", grupo_servico_id=43)
		ServicoFactory.create(id=217, descricao="Troca por defeito", grupo_servico_id=44)
		ServicoFactory.create(id=218, descricao="Recolhimento por não utilização", grupo_servico_id=44)
		ServicoFactory.create(id=219, descricao="Recolhimento para baixa", grupo_servico_id=44)
		ServicoFactory.create(id=220, descricao="Recolhimento para manutenção", grupo_servico_id=44)
		ServicoFactory.create(id=221, descricao="Solicitação de móvel/equipamento", grupo_servico_id=44)
		ServicoFactory.create(id=222, descricao="Alteração de local ou lotação de móvel/equipamento", grupo_servico_id=44)
		ServicoFactory.create(id=223, descricao="Troca por defeito", grupo_servico_id=45)
		ServicoFactory.create(id=224, descricao="Recolhimento por não utilização", grupo_servico_id=45)
		ServicoFactory.create(id=225, descricao="Recolhimento para baixa", grupo_servico_id=45)
		ServicoFactory.create(id=226, descricao="Recolhimento para manutenção", grupo_servico_id=45)
		ServicoFactory.create(id=227, descricao="Solicitação de móvel/equipamento", grupo_servico_id=45)
		ServicoFactory.create(id=228, descricao="Alteração de local ou lotação de móvel/equipamento", grupo_servico_id=45)
		ServicoFactory.create(id=229, descricao="Troca por defeito", grupo_servico_id=46)
		ServicoFactory.create(id=230, descricao="Recolhimento por não utilização", grupo_servico_id=46)
		ServicoFactory.create(id=231, descricao="Recolhimento para baixa", grupo_servico_id=46)
		ServicoFactory.create(id=232, descricao="Recolhimento para manutenção", grupo_servico_id=46)
		ServicoFactory.create(id=233, descricao="Solicitação de móvel/equipamento", grupo_servico_id=46)
		ServicoFactory.create(id=234, descricao="Alteração de local ou lotação de móvel/equipamento", grupo_servico_id=46)
		ServicoFactory.create(id=235, descricao="Troca por defeito", grupo_servico_id=47)
		ServicoFactory.create(id=236, descricao="Recolhimento por não utilização", grupo_servico_id=47)
		ServicoFactory.create(id=237, descricao="Recolhimento para baixa", grupo_servico_id=47)
		ServicoFactory.create(id=238, descricao="Recolhimento para manutenção", grupo_servico_id=47)
		ServicoFactory.create(id=239, descricao="Solicitação de móvel/equipamento", grupo_servico_id=47)
		ServicoFactory.create(id=240, descricao="Alteração de local ou lotação de móvel/equipamento", grupo_servico_id=47)
		ServicoFactory.create(id=241, descricao="Troca por defeito", grupo_servico_id=48)
		ServicoFactory.create(id=242, descricao="Recolhimento por não utilização", grupo_servico_id=48)
		ServicoFactory.create(id=243, descricao="Recolhimento para baixa", grupo_servico_id=48)
		ServicoFactory.create(id=244, descricao="Recolhimento para manutenção", grupo_servico_id=48)
		ServicoFactory.create(id=245, descricao="Solicitação de móvel/equipamento", grupo_servico_id=48)
		ServicoFactory.create(id=246, descricao="Alteração de local ou lotação de móvel/equipamento", grupo_servico_id=48)
		ServicoFactory.create(id=247, descricao="Troca por defeito", grupo_servico_id=49)
		ServicoFactory.create(id=248, descricao="Recolhimento por não utilização", grupo_servico_id=49)
		ServicoFactory.create(id=249, descricao="Recolhimento para baixa", grupo_servico_id=49)
		ServicoFactory.create(id=250, descricao="Recolhimento para manutenção", grupo_servico_id=49)
		ServicoFactory.create(id=251, descricao="Solicitação de móvel/equipamento", grupo_servico_id=49)
		ServicoFactory.create(id=252, descricao="Alteração de local ou lotação de móvel/equipamento", grupo_servico_id=49)
		ServicoFactory.create(id=253, descricao="Troca por defeito", grupo_servico_id=50)
		ServicoFactory.create(id=254, descricao="Recolhimento por não utilização", grupo_servico_id=50)
		ServicoFactory.create(id=255, descricao="Recolhimento para baixa", grupo_servico_id=50)
		ServicoFactory.create(id=256, descricao="Recolhimento para manutenção", grupo_servico_id=50)
		ServicoFactory.create(id=257, descricao="Solicitação de móvel/equipamento", grupo_servico_id=50)
		ServicoFactory.create(id=258, descricao="Alteração de local ou lotação de móvel/equipamento", grupo_servico_id=50)
		ServicoFactory.create(id=259, descricao="Troca por defeito", grupo_servico_id=51)
		ServicoFactory.create(id=260, descricao="Recolhimento por não utilização", grupo_servico_id=51)
		ServicoFactory.create(id=261, descricao="Recolhimento para baixa", grupo_servico_id=51)
		ServicoFactory.create(id=262, descricao="Recolhimento para manutenção", grupo_servico_id=51)
		ServicoFactory.create(id=263, descricao="Solicitação de móvel/equipamento", grupo_servico_id=51)
		ServicoFactory.create(id=264, descricao="Alteração de local ou lotação de móvel/equipamento", grupo_servico_id=51)
		ServicoFactory.create(id=265, descricao="Troca por defeito", grupo_servico_id=52)
		ServicoFactory.create(id=266, descricao="Recolhimento por não utilização", grupo_servico_id=52)
		ServicoFactory.create(id=267, descricao="Recolhimento para baixa", grupo_servico_id=52)
		ServicoFactory.create(id=268, descricao="Recolhimento para manutenção", grupo_servico_id=52)
		ServicoFactory.create(id=269, descricao="Solicitação de móvel/equipamento", grupo_servico_id=52)
		ServicoFactory.create(id=270, descricao="Alteração de local ou lotação de móvel/equipamento", grupo_servico_id=52)
		ServicoFactory.create(id=271, descricao="Troca por defeito", grupo_servico_id=53)
		ServicoFactory.create(id=272, descricao="Recolhimento por não utilização", grupo_servico_id=53)
		ServicoFactory.create(id=273, descricao="Recolhimento para baixa", grupo_servico_id=53)
		ServicoFactory.create(id=274, descricao="Recolhimento para manutenção", grupo_servico_id=53)
		ServicoFactory.create(id=275, descricao="Solicitação de móvel/equipamento", grupo_servico_id=53)
		ServicoFactory.create(id=276, descricao="Alteração de local ou lotação de móvel/equipamento", grupo_servico_id=53)
		ServicoFactory.create(id=277, descricao="Troca por defeito", grupo_servico_id=54)
		ServicoFactory.create(id=278, descricao="Recolhimento por não utilização", grupo_servico_id=54)
		ServicoFactory.create(id=279, descricao="Recolhimento para baixa", grupo_servico_id=54)
		ServicoFactory.create(id=280, descricao="Recolhimento para manutenção", grupo_servico_id=54)
		ServicoFactory.create(id=281, descricao="Solicitação de móvel/equipamento", grupo_servico_id=54)
		ServicoFactory.create(id=282, descricao="Alteração de local ou lotação de móvel/equipamento", grupo_servico_id=54)
		ServicoFactory.create(id=283, descricao="Troca por defeito", grupo_servico_id=55)
		ServicoFactory.create(id=284, descricao="Recolhimento por não utilização", grupo_servico_id=55)
		ServicoFactory.create(id=285, descricao="Recolhimento para baixa", grupo_servico_id=55)
		ServicoFactory.create(id=286, descricao="Recolhimento para manutenção", grupo_servico_id=55)
		ServicoFactory.create(id=287, descricao="Solicitação de móvel/equipamento", grupo_servico_id=55)
		ServicoFactory.create(id=288, descricao="Alteração de local ou lotação de móvel/equipamento", grupo_servico_id=55)
		ServicoFactory.create(id=289, descricao="Troca por defeito", grupo_servico_id=56)
		ServicoFactory.create(id=290, descricao="Recolhimento por não utilização", grupo_servico_id=56)
		ServicoFactory.create(id=291, descricao="Recolhimento para baixa", grupo_servico_id=56)
		ServicoFactory.create(id=292, descricao="Recolhimento para manutenção", grupo_servico_id=56)
		ServicoFactory.create(id=293, descricao="Solicitação de móvel/equipamento", grupo_servico_id=56)
		ServicoFactory.create(id=294, descricao="Alteração de local ou lotação de móvel/equipamento", grupo_servico_id=56)
		ServicoFactory.create(id=295, descricao="Troca por defeito", grupo_servico_id=57)
		ServicoFactory.create(id=296, descricao="Recolhimento por não utilização", grupo_servico_id=57)
		ServicoFactory.create(id=297, descricao="Recolhimento para baixa", grupo_servico_id=57)
		ServicoFactory.create(id=298, descricao="Recolhimento para manutenção", grupo_servico_id=57)
		ServicoFactory.create(id=299, descricao="Solicitação de móvel/equipamento", grupo_servico_id=57)
		ServicoFactory.create(id=300, descricao="Alteração de local ou lotação de móvel/equipamento", grupo_servico_id=57)
		ServicoFactory.create(id=339, descricao="Troca de porta", grupo_servico_id=68)

		# Instalações
		ServicoFactory.create(id=346, descricao="Manutenção de calhas", grupo_servico_id=71)
		ServicoFactory.create(id=347, descricao="Limpeza de calhas", grupo_servico_id=71)
		ServicoFactory.create(id=348, descricao="Substituição de telhas", grupo_servico_id=71)
		ServicoFactory.create(id=349, descricao="Manutenção de Rufos", grupo_servico_id=71)
		ServicoFactory.create(id=350, descricao="Aprimoramento dos sistemas de escoamento de água", grupo_servico_id=71)
		ServicoFactory.create(id=351, descricao="Conserto de telhas", grupo_servico_id=71)
		ServicoFactory.create(id=352, descricao="conserto de goivas", grupo_servico_id=71)
		ServicoFactory.create(id=353, descricao="Substituição de goivas", grupo_servico_id=71)
		ServicoFactory.create(id=354, descricao="torneiras - manutenção", grupo_servico_id=72)
		ServicoFactory.create(id=355, descricao="torneiras - substituição", grupo_servico_id=72)
		ServicoFactory.create(id=356, descricao="registros - manutenção", grupo_servico_id=72)
		ServicoFactory.create(id=357, descricao="registros - substituição", grupo_servico_id=72)
		ServicoFactory.create(id=358, descricao="mictórios - desentupimento", grupo_servico_id=72)
		ServicoFactory.create(id=359, descricao="mictórios - substituição de válvula - componentes", grupo_servico_id=72)
		ServicoFactory.create(id=360, descricao="mictórios - regulagem", grupo_servico_id=72)
		ServicoFactory.create(id=361, descricao="vasos sanitários - desentupimento", grupo_servico_id=72)
		ServicoFactory.create(id=362, descricao="vasos sanitários - substituição de válvula", grupo_servico_id=72)
		ServicoFactory.create(id=363, descricao="pias - manutenção de sifão", grupo_servico_id=72)
		ServicoFactory.create(id=364, descricao="pias - substituição de sifão", grupo_servico_id=72)
		ServicoFactory.create(id=365, descricao="tubulação de água - manutenção interna", grupo_servico_id=72)
		ServicoFactory.create(id=366, descricao="tubulação de água - manutenção externa", grupo_servico_id=72)
		ServicoFactory.create(id=367, descricao="Desentupimento em mictórios", grupo_servico_id=73)
		ServicoFactory.create(id=368, descricao="Desentupimento em vasos sanitários", grupo_servico_id=73)
		ServicoFactory.create(id=369, descricao="Desentupimento de ralos", grupo_servico_id=73)
		ServicoFactory.create(id=370, descricao="Limpeza de caixas de passagem", grupo_servico_id=73)
		ServicoFactory.create(id=371, descricao="Rede de Esgoto - manutenção e limpeza", grupo_servico_id=74)
		ServicoFactory.create(id=372, descricao="Limpeza de caixas de gordura", grupo_servico_id=74)
		ServicoFactory.create(id=373, descricao="Limpeza das caixas d'água", grupo_servico_id=76)
		ServicoFactory.create(id=374, descricao="Manutenção dos Portões", grupo_servico_id=77)
		ServicoFactory.create(id=375, descricao="Manutenção de grades", grupo_servico_id=77)
		ServicoFactory.create(id=376, descricao="Substituição de vidros quebrados", grupo_servico_id=78)
		ServicoFactory.create(id=377, descricao="Necessidades de alteração ou aprimoramento em Gabinetes e salas administrativas - instalação e substituição de janelas.", grupo_servico_id=79)
		ServicoFactory.create(id=378, descricao="Manutenção de componentes", grupo_servico_id=79)
		ServicoFactory.create(id=379, descricao="Verificação nos registros", grupo_servico_id=80)
		ServicoFactory.create(id=380, descricao="Contato, acompanhamento e fiscalização sobre as contratadas para a Manutenção das Bombas de Água;", grupo_servico_id=80)
		ServicoFactory.create(id=381, descricao="Elevador Parado - Contato, acompanhamento e fiscalização sobre as contratadas para a Manutenção dos Elevadores.", grupo_servico_id=81)
		ServicoFactory.create(id=382, descricao="Elevadores parados com usuário preso - Contato com COPRAF e Contato, acompanhamento e fiscalização sobre as contratadas para a Manutenção dos Elevadores.", grupo_servico_id=81)
		ServicoFactory.create(id=385, descricao="Serviços em alvenaria: rachaduras em paredes e inovações nos Predios da Câmara", grupo_servico_id=84)
		ServicoFactory.create(id=386, descricao="Pisos: inovações nos Predios da Câmara, pisos cerâmicos soltos ou quebrados", grupo_servico_id=84)
		ServicoFactory.create(id=387, descricao="Portas: porta empenada, manutenção ou substituição de portas, trincos e/ou maçanetas", grupo_servico_id=84)
		ServicoFactory.create(id=388, descricao="Serviços gerais de marcenaria; ajustes em materiais de madeira", grupo_servico_id=84)
		ServicoFactory.create(id=389, descricao="Pintura", grupo_servico_id=84)
		ServicoFactory.create(id=390, descricao="DRYWALL: manutenção instalação e retirada de divisórias em drywall, Necessidades de alteração ou aprimoramento em Gabinetes e salas administrativas", grupo_servico_id=84)
		ServicoFactory.create(id=391, descricao="DIVISÓRIAS NAVAIS: manutenção, instalação e retirada de divisórias navais; Necessidades de alteração ou aprimoramento em Gabinetes e salas administrativas", grupo_servico_id=84)
		ServicoFactory.create(id=392, descricao="FORROS PVC: manutenção, instalação e retirada de forros PVC; Necessidades de alteração ou aprimoramento em Gabinetes e salas administrativas", grupo_servico_id=84)
		ServicoFactory.create(id=393, descricao="FORROS EM GESSO: manutenção, instalação e retirada de forros em Gesso; Necessidades de alteração ou aprimoramento em Gabinetes e salas administrativas", grupo_servico_id=84)
		ServicoFactory.create(id=394, descricao="FORROS EM DRYWALL: manutenção, instalação e retirada de forros de drywall; Necessidades de alteração ou aprimoramento em Gabinetes e salas administrativas", grupo_servico_id=84)
		ServicoFactory.create(id=395, descricao="Manutenção em infiltrações", grupo_servico_id=84)
		ServicoFactory.create(id=396, descricao="LÂMPADAS: Substituição de Lâmpadas e/ ou Reatores Queimados", grupo_servico_id=85)
		ServicoFactory.create(id=397, descricao="LUMINÁRIAS: Substituição, Manutenção e Instalação de Luminárias; Luminárias com defeito; necessidades de alteração ou aprimoramento em Gabinetes e salas administrativas com Luminárias.", grupo_servico_id=85)
		ServicoFactory.create(id=398, descricao="ILUMINAÇÃO EXTERNA - Aprimoramento de Iluminação externa; Substituição, Manutenção e Instalação de Refletores", grupo_servico_id=85)
		ServicoFactory.create(id=399, descricao="TOMADAS - Manutenção e Instalação", grupo_servico_id=85)
		ServicoFactory.create(id=400, descricao="INTERRUPTORES - Manutenção e Instalação", grupo_servico_id=85)
		ServicoFactory.create(id=401, descricao="FALTA DE LUZ - Manutenção, instalação de Disjuntores; Manutenção; Instalação e distribuição de Quadros de Energia", grupo_servico_id=85)
		ServicoFactory.create(id=402, descricao="PONTOS DE REDE: Manutenção, instalação e alteração de pontos de rede; Necessidades de alteração ou aprimoramento em Gabinetes e salas administrativas", grupo_servico_id=85)
		ServicoFactory.create(id=403, descricao="TELEFONIA - Manutenção, instalação e alteração de pontos de telefone; Necessidades de alteração ou aprimoramento em Gabinetes e salas administrativas", grupo_servico_id=85)

	def popula_localizacao(self):
		self.stdout.write('...populando Localizacao')				

	def popula_pavimento(self):
		self.stdout.write('...populando Pavimento')						

	def handle(self, *args, **options):
		if options['palavra_magica'] != 'ZACA':
			self.stdout.write('##### Você precisa digitar a palavra mágica para executar o script #####')
			sys.exit(1)
		else:
			self.popula_setor_chamado()
			self.popula_grupo_servico()
			self.popula_servico()
			self.popula_localizacao()
			self.popula_pavimento()

			self.stdout.write('Carga completada com sucesso.')				