# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.RunSQL(
            """
            DROP TABLE IF EXISTS v_setor;
 
            CREATE TABLE v_setor (
                set_id serial primary key,
                set_nome character varying(500) not null,
                set_sigla character varying(100) not null,
                set_id_superior integer,
                set_ativo boolean not null, 
                set_tipo character varying(1)
            );

            """
        ),
        migrations.RunSQL("INSERT INTO v_setor(set_id, set_nome, set_sigla, set_id_superior, set_ativo, set_tipo) VALUES(171, 'Divisão de Desenvolvimento De Sistemas', 'DDS-1', 1, 't', 'N');"),
        migrations.RunSQL("INSERT INTO v_setor(set_id, set_nome, set_sigla, set_id_superior, set_ativo, set_tipo) VALUES(172, 'Divisão de Suporte em Informática', 'DSI-2', 1, 't', 'N');"),
    ]
