# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-21 09:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ramal', models.CharField(blank=True, max_length=15, null=True)),
                ('assunto', models.CharField(blank=True, max_length=200, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_abertura', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta')], default='NORMAL', max_length=10)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('ATENDIMENTO', 'Em Atendimento'), ('FECHADO', 'Fechado')], default='ABERTO', max_length=15)),
                ('data_fechamento', models.DateTimeField(null=True)),
                ('novidade', models.BooleanField(default=False)),
                ('patrimonio', models.CharField(blank=True, max_length=100, null=True)),
                ('setor_solicitante', models.IntegerField(blank=True, null=True)),
                ('reaberto', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChamadoAnexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ImageField(upload_to='imagens')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='core.Chamado')),
            ],
        ),
        migrations.CreateModel(
            name='ChamadoResposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('resposta', models.TextField()),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Chamado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Respostas para o Chamado',
            },
        ),
        migrations.CreateModel(
            name='FilaChamados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Chamado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Fila de Chamados',
            },
        ),
        migrations.CreateModel(
            name='GrupoServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=300)),
                ('patrimonio_obrigatorio', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Grupo de Serviços',
            },
        ),
        migrations.CreateModel(
            name='HistoricoChamados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=15)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Chamado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Histórico do Chamado',
            },
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Localizações',
            },
        ),
        migrations.CreateModel(
            name='Pavimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=300)),
                ('localizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Localizacao')),
            ],
            options={
                'verbose_name_plural': 'Pavimentos',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=300)),
                ('grupo_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.GrupoServico')),
            ],
            options={
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='SetorChamado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor_id', models.IntegerField(unique=True)),
                ('recebe_chamados', models.BooleanField(default=False)),
                ('localizacao', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Setores Chamados',
            },
        ),
        migrations.AddField(
            model_name='gruposervico',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SetorChamado'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='grupo_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.GrupoServico'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='localizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Localizacao'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='pavimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Pavimento'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Servico'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SetorChamado'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
